### ISSUE TITLE
Author name, year and project name missing in LICENSE file

### ISSUE THREAD

**Issue by danbelov** [Allexin/TrackYourTime#10]
Line number 655 of the LICENSE file requires the following information:

{project} Copyright (C) {year} {fullname}

but it is still missing.

I wanted to create a pull request, but i think it must be written by the author only.

**Comment by Allexin** [comment]
I think this is required only for terminal applications. not for gui:
"If the program does terminal interaction, make it output a short notice like this when it starts in an interactive mode"
and even checksystem app not required this because it's non interactive app.
No?

**Comment by danbelov** [comment]
Yes, you are right, i haven't just read it thoroughly. I think this issue may be closed now
