### ISSUE TITLE
Какое то окно вылазит и мешает

### ISSUE THREAD

**Issue by jekeam** [Allexin/TrackYourTime#102]
Что это за окно вылазит постоянно, и как его убрать? И оно еще и криво вылазит, не учитывает положение моей панели
![image](https://user-images.githubusercontent.com/19660852/92867040-a488a600-f419-11ea-8ea9-8db3f8cf8a3a.png)

**Comment by Allexin** [comment]
В настройках положение вид и всё остальное по этому окну настраивается.
Окно для того, чтобы динамически задавать категорию для каждого приложения.
А также чтобы напоминать о текущем типе активности(цветом фона)

**Comment by jekeam** [comment]
> В настройках положение вид и всё остальное по этому окну настраивается.
> Окно для того, чтобы динамически задавать категорию для каждого приложения.
> А также чтобы напоминать о текущем типе активности(цветом фона)

Как сделать чтоб оно вылезало только если категория не задана? так же скайп не трекается - не вылазит на нем?
