### ISSUE TITLE
Расширение для Chrome не доступно для скачивания из Chrome Web Store

### ISSUE THREAD

**Issue by 9maksim** [Allexin/TrackYourTime#104]
Ссылка для скачивания https://chrome.google.com/webstore/detail/trackyourtime-chrome-trac/iaddggcinldmlkcmdgnajpddncpoanhd не работает

**Comment by Allexin** [comment]
Гугл удалил.

**Comment by 9maksim** [comment]
Все расширения в папке \TrackYourTime\data\app_predef
