### ISSUE TITLE
Wrong application path tooltip under Windows

### ISSUE THREAD

**Issue by vapaamies** [Allexin/TrackYourTime#11]
For example, C:/Device/HarddiskVolume1/Tools/Pet.exe should be C:\Tools\Pet.exe or something like \.\Device\HarddiskVolume1\Tools\Pet.exe.

**Comment by Allexin** [comment]
At this point i have no idea how to get more accurate path.

**Comment by vapaamies** [comment]
cexternaltrackers.h, cExternalTrackers::getExternalTrackerState method:
    TrackerName.path = appName.path+"/"+appName.fileName;
I think the bug is here, but don't know how to fix it.

**Comment by Allexin** [comment]
We will not fix this issue. Main goal of tooltips - make tip for user to understand what application is. And tooltip get this information for user even if path is not 100% correctly.
