### ISSUE TITLE
checksystem does'nt detect absence of libQt5Core.so.5 and libQt5Widgets.so.5 under Linux 

### ISSUE THREAD

**Issue by zirf0** [Allexin/TrackYourTime#12]
I used clear (without Qt5)  CentOS 7.2

$ ./checksystem
./checksystem: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
$ sudo yum install qt5-qtbase
......
$ ./checksystem
X Window system - OK
$ ./TrackYourTime
./TrackYourTime: error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No such file or directory
$ sudo yum install qt5-qtbase-gui
...
For now, it's ok.
Please add appropriate verification.

PS For RHEL/CentOS 7 just: 
$ sudo yum -y install qt5-qtbase qt5-qtbase-gui 
is enouth if you don't use qt5 for something else.

**Comment by Allexin** [comment]
Fixed in 0.9.2 release
