### ISSUE TITLE
Make AutoUpdater and repo in linux

### ISSUE THREAD

**Issue by Oplkill** [Allexin/TrackYourTime#18]
Autoupdater need to keep latest version for users.

**Comment by Allexin** [comment]
Have no idea how to do it right.

**Comment by Oplkill** [comment]
Firstly you can make checking for latest version and refer user download new version. Just connect to github version.txt file. (put that file in release category and update this file when you updating programm)

And as a second
1) Create in github installed folder in release category(Or create your own web site)
2) Create single programm for install and replace files of programm
3) Refer user close the programm and install latest updates

PS: Короче создай файл текстовик в гитхабе, который будет содержать в себе цифру последней версии для того чтобы сверять с локальной версией юзера(сылка нужна прямая, помойму такие есть в релизной категории.
А потом уже создай отдельную программу, которая банально будет заменять файлы и докачивать новые.(можно также тобы она качала с гита, где будет лежать распакованная версия программы)

**Comment by Allexin** [comment]
Посмотрел варианты для линукса и винды. Вроде бы нет проблем реализовать автоматическое обновление: проверили версию, скачали архив, распаковали. А вот под маком что-то всё совсем печально.

**Comment by f2404** [comment]
For Linux, it's better to rely on the package manager rather than on a custom update tool.
For example, Firefox is not able to update itself (unlike when on Windows) - at least when installed by the package manager.

**Comment by Allexin** [comment]
It's impossible to support all package managers in all distros.

**Comment by f2404** [comment]
It's the distros that should support your application, not you :)

**Comment by Allexin** [comment]
My app is not popular enough. :(

**Comment by f2404** [comment]
I mean, the custom updater could be a temporary solution. But when (if) your application gets into distros' repositories, you'll have to deal with it and disable the custom updater.

**Comment by Allexin** [comment]
In next version i am add updates checker. But user must manually download and install update.
I do not trust available updaters, and i can't create 100% correct cross-platform updater. I think - update checker - good solution.

**Comment by Allexin** [comment]
Version checker now available in 0.9.2.1
Добавлена проверка обновлений в версии 0.9.2.1
