### ISSUE TITLE
Размеры шрифтов из Windows

### ISSUE THREAD

**Issue by Lenchik** [Allexin/TrackYourTime#21]
Хорошо бы брать размеры шрифтов из настроенных пользователем. Соответственно подбирать и размеры кнопочек.
На скриншоте видно, что в списке программ шрифт из увеличенных пользователем, а в левой зоне всё мелкое, да и выше тоже мелко. Обычно размер шрифта правят неспроста.
![clipboard-1](https://cloud.githubusercontent.com/assets/2931130/12535683/22e8a36a-c29c-11e5-81a2-78953efb6348.jpg)

**Comment by Allexin** [comment]
Fixed in 0.9.2 release and checked on Windows 8.1. Fonts increasing works fine.
