### ISSUE TITLE
building trouble

### ISSUE THREAD

**Issue by greyfenrir** [Allexin/TrackYourTime#25]
Hi.
Need help with building.
I'm trying to build app in ubuntu 14.04 amd64
In qt-creator I select pro-file, release, run.
Unfortunately I got next error:

> <path>/TrackYourTime/TrackYourTime/cdatamanager.cpp: -1: In constructor 'cDataManager::cDataManager()':
> <path>/TrackYourTime/TrackYourTime/cdatamanager.cpp:59: error: 'AppDataLocation' is not a member of 'QStandardPaths'
>      m_StorageFileName = QStandardPaths::writableLocation(QStandardPaths::AppDataLocation)+"/db.bin";

I use qt-creator for the first time, sorry if there is any stupid mistake.)

**Comment by Allexin** [comment]
i think you use Qt with version < 5.4
AppDataLocation available only in Qt 5.4 or later

**Comment by greyfenrir** [comment]
Ok, I registered and downloaded new qt. Then I run creator (based on Qt 5.5.1) and got the same error. 
Should I do anything more?

**Comment by Allexin** [comment]
clean, rebuild.
also delete file TrackYourTime.pro.user and configure project(qt creator automatically starts this if pro.user not found)

**Comment by greyfenrir** [comment]
I did what you advise, but error is still there.

**Comment by Allexin** [comment]
Please make screenshot of configuration window. Like this:
![](http://funkyimg.com/i/26UfT.png)

**Comment by greyfenrir** [comment]
It seems I saw these options before, but when I tried to make the screenshot - it worked ... )
Thanks for your time and good luck!
