### ISSUE TITLE
Программа не запускается на OS X 10.8.5

### ISSUE THREAD

**Issue by mastaka** [Allexin/TrackYourTime#26]
Process:         TrackYourTime [1214]
Path:            /Applications/TrackYourTime.app/Contents/MacOS/TrackYourTime
Identifier:      com.yourcompany.TrackYourTime
Version:         ???
Code Type:       X86-64 (Native)
Parent Process:  launchd [178]
User ID:         501

Date/Time:       2016-01-24 17:39:33.322 +0100
OS Version:      Mac OS X 10.8.5 (12F2560)
Report Version:  10

Crashed Thread:  0

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

**Dyld Error Message:
  Library not loaded: @rpath/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Applications/TrackYourTime.app/Contents/MacOS/TrackYourTime
  Reason: image not found**

Binary Images:
       0x10f88b000 -        0x10f8bcff7 +com.yourcompany.TrackYourTime (???) <9EDA29CB-C4FC-39B6-BD71-FD28D5C8105E> /Applications/TrackYourTime.app/Contents/MacOS/TrackYourTime
    0x7fff6f48b000 -     0x7fff6f4bf94f  dyld (210.2.3) <8958FE97-5830-3928-BC38-23136E7D3783> /usr/lib/dyld
    0x7fff845fc000 -     0x7fff845fcfff  com.apple.ApplicationServices (45 - 45) <A3ABF20B-ED3A-32B5-830E-B37831A45A80> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff8b786000 -     0x7fff8c3b3fff  com.apple.AppKit (6.8 - 1187.40) <F12CF463-6F88-32ED-9EBA-0FA2AD3CF576> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit

**Comment by Allexin** [comment]
Fixed in 0.9.2 release
