### ISSUE TITLE
Добавьте в README текст на русском

### ISSUE THREAD

**Issue by kv4** [Allexin/TrackYourTime#3]
Привет!
Добавьте пожалуйста в README описание на русском. Это кажется ничему не противоречит.

**Comment by mkwork** [comment]
Imho, it's bad idea ^_^. You can just try to review some Japan vim plugins which have great abilities but aren't using by anybody also while their documentation is pure.

I though it's a better idea to ask author to put localized build artifacts through [appveyor](http://www.appveyor.com/docs) and [travis CI](https://docs.travis-ci.com/) ;)

**Comment by Allexin** [comment]
At this point i have no idea how to use appveyor or travis Cl. I'll try to fix it.

**Comment by unreal666** [comment]
Создать отдельный файл README_RU.md или типа того.
Т.к. автор не супер спец по англ. языку, то лучше все-таки иметь отдельный readme на родном языке.

**Comment by vazhnov** [comment]
Поддерживаю идею про отдельный README_RU, и для русскоязычных пользователей поисковых систем будет полезно.

**Comment by alexrett** [comment]
Поддерживаю, было бы здорово иметь чуть больше документации на русском, в конце концов сообщество могло бы перевести ее позже на английский. Например сделать как у проекта https://github.com/fenom-template/fenom

**Comment by MPolovyi** [comment]
Присоединяюсь к @alexrett, по возможности поучавствую в переводе
Кроме того раз проект в C++ то возможно doxygen будет лучшим вариантом?
Например как здесь: https://github.com/mikael-s-persson/ReaK

**Comment by Allexin** [comment]
https://github.com/fenom-template/fenom - выглядит хорошим вариантов.

по поводу doxygen - пока ИМХО не имеет смысла прикручивать автоматический генератор документации. Если вдруг кто захочет в исходниках поковыряться - сразу по месту комментарии увидит. а снаруже именно по исходникам от документации смысла нет - это же не API.
