### ISSUE TITLE
java apps have been detected as sun-awt-X11-...

### ISSUE THREAD

**Issue by kkamkou** [Allexin/TrackYourTime#30]
Hi! Thank you for the app! Unfortunately any java application is detected as `sun-awt-X11-XFramePeer` or `sun-awt-X11-XDialogPeer`. You can simulate it by downloading any trial version of `PyCharm` or `WebStrom`.

**Comment by Allexin** [comment]
Everyone:
any ideas how to detect what happend inside JVM?

**Comment by akalinkin** [comment]
wids=( $(xprop -root | grep '_NET_CLIENT_LIST._(WINDOW)' | sed 's/^._#//' | sed 's/,/\n/g' | sort -u ) )
for w in ${wids[@]}; do echo id: $w; xprop -id $w | grep -P '_NET_WM_PID|^WM_NAME'; done

Это в консоли UBUNTU. Может частный случай. Но позволяет получать и Тайтл для активной вкладки браузера и для Java приложений
Вот как выглядит открытый проект PhpStrom:

id: 0x4000048
_NET_WM_PID(CARDINAL) = 12818
WM_NAME(STRING) = "bponline.local - [~/projects/bponline.local] - .../src/AppBundle/Manager/VirtualBillingManager.php - PhpStorm 9.0.2"

**Comment by Allexin** [comment]
Ага. Анализ заголовка в впланах уже.

**Comment by Allexin** [comment]
Fixed in 0.9.2 release

**Comment by spankratov** [comment]
PyCharm и CLion всё ещё отображаются как sun-awt-X11-XFramePeer и sun-awt-X11-XDialogPeer.
