### ISSUE TITLE
Autostart schedule, working days and hours

### ISSUE THREAD

**Issue by Daist** [Allexin/TrackYourTime#31]
В данный момент нет возможности выбрать профиль автоматически в зависимости от дня недели и времени суток, т.е. включать и выключать учёт для рабочего времени нужно вручную. Можно ли это добавить в настройки? Скажем, 8:00-18:00 - профиль 1, 18:00-8:00 - профиль 2.

**Comment by Allexin** [comment]
Fixed in 0.9.2 release
