### ISSUE TITLE
Mac os 10.10.5 Doesn't run

### ISSUE THREAD

**Issue by SuhanovO** [Allexin/TrackYourTime#32]
I compiled application, but when run i see this error

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
  Referenced from: /Users/USER/Downloads/*/TrackYourTime.app/Contents/MacOS/TrackYourTime
  Reason: Incompatible library version: TrackYourTime requires version 64.0.0 or later, but ApplicationServices provides version 1.0.0

Binary Images:
    0x7fff66b80000 -     0x7fff66bb6887  dyld (353.2.3) <D9967621-6378-381B-A47B-5085EE476B62> /usr/lib/dyld
    0x7fff909d5000 -     0x7fff909d5fff  com.apple.ApplicationServices (48 - 48) <5BF7910B-C328-3BF8-BA4F-CE52B574CE01> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices

**Comment by Allexin** [comment]
Fixed in 0.9.2 release
