### ISSUE TITLE
Save window title

### ISSUE THREAD

**Issue by nshopik** [Allexin/TrackYourTime#33]
Добавьте возможность сохранять названия окна в статистике (подгруппа для конкретного исполнямого файла). Иначе часть приложении слишком абстрактно для статы

**Comment by akalinkin** [comment]
Согласен это важнее чем просто _chromium-browser_

Вот, например, что можно выдернуть в UBUNTU (и прочих линуксах)
wids=( $(xprop -root | grep '_NET_CLIENT_LIST._(WINDOW)' | sed 's/^._#//' | sed 's/,/\n/g' | sort -u ) )
echo number of registered windows: ${#wids[@]}
for w in ${wids[@]}; do echo id: $w; xprop -id $w | grep -P '_NET_WM_PID|^WM_NAME'; done

Здесь уже интересней информация:

id: 0x3c000f8
WM_NAME(UTF8_STRING) = "Window title from PID (script) [Archive] - Ubuntu Forums – Chromium"
_NET_WM_PID(CARDINAL) = 2525

**Comment by nshopik** [comment]
В винде я получал эти данные вот так, когда писал аналог на питоне

```
hwnd = GetForegroundWindow()
curwtext = GetWindowText(hwnd)
```

Для браузеров конечно можно плагины сделать, чтобы еще URL получать. Но еще остаеться много мульти-задачных приложении, которые нужно разбирать детально и заголовок решил бы эту проблему

**Comment by akalinkin** [comment]
По аналогии с ReacueTime можно сделать БД с правилами парсинга тех же ЗаголовковВкладокБраузеров (и не только браузеров да) и соотносить их с нужной категорией в последствии. Эту БД можно постепенно наработать и обновлять как модуль приложения. А уж пользовательские категории это личное дело каждого только приоритет у них должен быть выше общей системной БД правил.

**Comment by Allexin** [comment]
Да, я хочу сделать возможность приложениям назначать regexp для разбора заголовка и, соответственно, сделать файлик с набором регэкспов под стандартные приложения, которые пополнять.
Проблема сейчас в другом - как это дело адекватно впихнуть в интерфейс, чтобы не было заграмождения и при этом всё удобно раскладывалось.
Идеи уже есть, но реализация не на 10 минут.

Хотя может быть лучше не regexp, а скрипт, на lua например. тогда гораздо больше простор для творчества. А сложность близкая, один фиг большинство пользователей не способны regexp составить.

**Comment by nshopik** [comment]
Визуально сделать стрелочкой для каждого исполняемого файла как сейчас в категориях, при нажатии которой открываеться еще список с заголовками (сортированными по времени). Даже такой простой вариант уже помог. В линуксе к тому же часто исполнямые файлы передаються странные, допустим вместо `thunerbird` оно передает значение `Mail`, поэтому заголовки нужны даже простые без регулярок

**Comment by zedxxx** [comment]
> Хотя может быть лучше не regexp, а скрипт, на lua например. тогда гораздо больше простор для творчества

Да, скрипт лучше.

**Comment by tonal** [comment]
Регекспы таки проще в реализации - в Qt они вшиты.
Я голосую за регекспы. Хотя если хочется оставить простор для творчества, можно просто предусмотреть возможность расширения конфига/базы.
Да, кстати в qt можно задействовать JavaScript - он тоже вшит.
Так что кандидатов аж 3, на вскидку. :)

**Comment by Oplkill** [comment]
Также надо учесть исключения для отдельных приложений. Например для браузера с функцией инкогнито. Главное чтобы юзер мог сам настроить исключения и на будущее добавить возможность удалять выбранное.

**Comment by Allexin** [comment]
Fixed in 0.9.2 release

**Comment by nshopik** [comment]
@Allexin Все облазил, но не вижу нигде заголовки в стате. Вижу лишь стрелочку в стате напротив исполняемого файла, нажав на нее вижу еще раз название исполняемого файла(default), это здесь должно же быть?

**Comment by Allexin** [comment]
Заголовок сохраняется при условии, что написан скрипт, который этот заголовок корректно обрабатывает. Если тупо в лоб брать заголовки - статистика превратится в нечитаемую кашу.
Подробнее здесь:
https://github.com/Allexin/TrackYourTime/wiki/%D0%A0%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%BE-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F#%D0%A2%D1%80%D1%8D%D0%BA%D0%B8%D0%BD%D0%B3-%D0%B0%D0%BA%D1%82%D0%B8%D0%B2%D0%BD%D0%BE%D1%81%D1%82%D0%B8-%D0%BD%D0%B0-%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%B5-%D0%B7%D0%B0%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BA%D0%B0-%D0%BE%D0%BA%D0%BD%D0%B0
