### ISSUE TITLE
Проверка ckechsystem не видит беспроводные и USB устройства ввода

### ISSUE THREAD

**Issue by akalinkin** [Allexin/TrackYourTime#34]
В моем случае есть клавиатура (беспроводная) но проверка говорит об обратном. Суть в том что в записи значится не _keyboard_ а _kbd_

sudo ls -lah /dev/input/by-id/

usb-2.4G_KB_2.4G_Mouse-event-kbd -> ../event3

**Comment by tonal** [comment]
То же самое при клаве подключенной по USB на ноуте:

```
$ls -l /dev/input/by-id/
lrwxrwxrwx 1 root root  9 янв.  26 09:32 usb-04f3_0103-event-kbd -> ../event6
```

**Comment by akalinkin** [comment]
Думаю надо вместо хардкода в 
TrackYourTime/checksystem/checksystem/main.cpp

Line 83:    QStringList keyboards = dir.entryList(QStringList() << "_keyboard_");

Объявить массив возможных events и использовать его.

**Comment by Allexin** [comment]
хорошая мысль. вынесу пути для поиска клавиатур в конфиг

**Comment by akalinkin** [comment]
Я думаю что не в конфиг даже. А просто в заголовок константами или файл с константами. Хотя конфиг без перекомипяции будет работать конечно.

**Comment by dniku** [comment]
То же самое что https://github.com/Allexin/TrackYourTime/issues/24

**Comment by Allexin** [comment]
Fixed in 0.9.2 release
