### ISSUE TITLE
Периодически падает

### ISSUE THREAD

**Issue by tonal** [Allexin/TrackYourTime#35]
Периодически падает со следующим диагнозом:

```
./TrackYourTime: symbol lookup error: ./TrackYourTime: undefined symbol: _ZN7QString13toUtf8_helperERKS_
```

ОС: Kubuntu 14.04 + все обновления + linux-image-generic-lts-vivid (linux-image-3.19.0-47)
KDE 4.14.13 из Kubuntu Backports ppa
Qt 4.8.6 - штатная
qtbase5-dev 5.2.1 - из стандартного репозитория

**Comment by Allexin** [comment]
Периодически - это каждые 25 минут?

**Comment by tonal** [comment]
Гарантированно падает при попытке сохранить настройки.
Похоже вылетает и при периодическом сохранении.

**Comment by tonal** [comment]
Причём конфиг таки меняется - при следующем запуске значения уже изменённые

**Comment by Allexin** [comment]
понятно почему падает - и сохранение БД и сохранение настроек происходит в utf8, в то время как Qt работает в другом формате. При попытке конвертнуть и падает. Вот только непонятно, почему этого метода нет в QT либах...

**Comment by f2404** [comment]
Погуглил "undefined symbol: _ZN7QString13toUtf8_helperERKS_" и нашёл вот это: http://stackoverflow.com/questions/27714446/undefined-symbol-zn7qstring13toutf8-helpererks-at-runtime
Может, собираете как-то не так?

**Comment by Allexin** [comment]
Попробую добавить флаг DQT_COMPILING_QSTRING_COMPAT_CPP.
Спасибо.

**Comment by Allexin** [comment]
Fixed in 0.9.2 release
