### ISSUE TITLE
Бинарники под linux не запускаются

### ISSUE THREAD

**Issue by mxite** [Allexin/TrackYourTime#37]
$ ./checksystem 
zsh: Ошибка формата выполняемого файла: ./checksystem
$ ./TrackYourTime 
zsh: Ошибка формата выполняемого файла: ./TrackYourTime

openSUSE 13.2 32бит

**Comment by f2404** [comment]
Наверное, потому что бинарники 64-битные?

**Comment by Allexin** [comment]
Да, сейчас сборки для 32 бит нету. Следующие релизы постараюсь делать и для 32 бит тоже.
Добавил в название архива 64, чтобы не вводить в заблуждение.

**Comment by Allexin** [comment]
Fixed in 0.9.2 release
