### ISSUE TITLE
Were .exe file?

### ISSUE THREAD

**Issue by zetaap** [Allexin/TrackYourTime#4]
"Extract archive with windows app in any folder and launch TrackYourTime.exe."

I did not find .exe file for Windows. Were is it?

**Comment by Allexin** [comment]
![snapshot5](https://cloud.githubusercontent.com/assets/5699510/12530506/484d1924-c1f2-11e5-85dc-db4023f5059c.png)

**Comment by aizenbit** [comment]
There is no such file in repository. Also I didn't find any .zip archive or download link.

**Comment by Allexin** [comment]
If i am right understand github guidlines - all binaries must be in release section, not in repository directly. Repository only for source code.

**Comment by aizenbit** [comment]
Yes you are right. =) This was my inattention.
