### ISSUE TITLE
Wrong notification appearance on Windows 10

### ISSUE THREAD

**Issue by khlopko** [Allexin/TrackYourTime#41]
Когда приложение только запускается или если уже запущенно и открыть трей, или открыть "Пуск", то появляется примерно 10 раз подряд (появилось, пол секунды, исчезло и снова появилось) сообщение от системы с текстом "Default: Uncategorized". В данном случае, оно полностью перекрывает еще и сам трей и я пару минут пытался просто попасть по иконке что бы открыть приложение.

On app start or if an app has already started and you open tray or "Start" menu, about 10 times appeared system notification "Default: Uncategorized". And this notification overlay system tray, what makes opening this app or other apps in tray harder.

**Comment by Daist** [comment]
Да, в десятке уведомления по-новому оформлены, так что я у себя их сразу отключил в настройках этой программы, даже по значку попасть было проблематично.

**Comment by Allexin** [comment]
В 0.9.2 будет возможность не только отключить уведомления, но и переключить не на системные, а на внутренние реализованные средствами приложения.
Внутренние уведомления исчезают при наведении на них мышки и их можно поместить в любом месте экрана.
