### ISSUE TITLE
Save settings in the *.exe directory

### ISSUE THREAD

**Issue by nagimov** [Allexin/TrackYourTime#42]
**Windows version - feature request**
The app is almost portable-ready now (works without registry access, db can be saved to the app location, etc.), but the default DB location after the first launch is always `%USERDIR%\...\db.bin`.
To make the app even more portable-ready (i.e. to be able to launch it from a thumb drive) it'll be very useful to have the possibility to save all the settings (including relative path to the db starting from program directory, i.e. `db_path = ".\db.bin"`) in the program directory, so it will be possible to launch it from thumb drives. And if there is no `settings.conf`in the program directory, just launch the app normally.

**Comment by Allexin** [comment]
good idea

**Comment by Allexin** [comment]
Fixed in 0.9.2 release
