### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by Straven** [Allexin/TrackYourTime#44]
На openSUSE 42.1 x64 через пару дней работы перестала запускаться.
При запуске через терминал получаю вот такое сообщение:

```
$ ./TrackYourTime 
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
[1]    8895 abort      ./TrackYourTime
```

При запуске в обычном режиме висит в трее, но при поптыке как-то пообщаться с приложением (клик кнопкой мыши по иконке) тут же вылетает.

**Comment by Allexin** [comment]
Вероятно поврежден файл базы данных с активностью.
Попробуйте переименовать db.bin, чтобы к нему не было доступа.
Если это поможет, то я был бы благодарен за ссылку на ваш файл с активностью, чтобы я мог проанализировать что в нем сломалось. Понимаю что это личная информация, поэтому не настаиваю.

**Comment by f2404** [comment]
Может быть, ловить эксепшены от `new` и `new []`, чтобы выдавать более понятное сообщение об ошибке?

**Comment by Allexin** [comment]
Можно обернуть весь код в main в эксцепшн и выводить в случае краша всю информацию в лог, как тут товарищ предлагал:
https://github.com/Allexin/TrackYourTime/issues/38
Наверно так и сделаю в следующей версии.

**Comment by f2404** [comment]
Весь код... а как понять, кто именно кинул тот же bad_alloc, например? стэк трейс выводить - понадобится своя имплементация для каждой платформы.

**Comment by Allexin** [comment]
Для части платформ если сделаю - уже хорошо.
перекрывать new и new[] не рискну, потому что это же Qt, она сама там много за кадром мутит. Могу стабильность поломать.
К примеру тот же std::bad_alloc - он не в моем коде падает. У меня вообще нигде не используется std, всё Qtшное только.

**Comment by Straven** [comment]
> Вероятно поврежден файл базы данных с активностью.
> Попробуйте переименовать db.bin, чтобы к нему не было доступа.
> Если это поможет, то я был бы благодарен за ссылку на ваш файл с активностью, чтобы я мог проанализировать что в нем сломалось. Понимаю что это личная информация, поэтому не настаиваю.

Постпил по совету. Пока работает. Если сломается еще раз пришлю файл. Пока что закрываю.
