### ISSUE TITLE
Change window decorator theme when change profile

### ISSUE THREAD

**Issue by Allexin** [Allexin/TrackYourTime#45]
Sometimes i and other users forget change profile because do not remember which profile is current now.
I want to add possibility to set different themes for profiles. It's good indicator.
But i have not clear vision - how to change theme programmatically?
I you, reader, know solution - please write here.
Actual environments:
KDE
Gnome
Unity
MS Windows default environment
Mac OS X default environment

Иногда я и другие пользователи забываем переключать профиль потому что не помним, какой профиль активен сейчас.
Я хочу добавить возможность устанавливать разные темы для профилей.
Но пока я не вижу способов это сделать.
Если ты, читатель, знешь как менять тупы в какоми нибудь окружении - напиши здесь.
Актуальные декораторы:
KDE
Gnome
Unity
MS Windows стандартное окружение
Mac OS X стандартное окружение

**Comment by aizenbit** [comment]
Если я правильно понял, о чём идёт речь, то [Qt Style Sheets](https://doc.qt.io/qt-5/stylesheet.html) могут помочь.

**Comment by Allexin** [comment]
Нее. Речь не о том, чтобы сменить скин самого приложения. Это бессмысленно.
Речь о том, чтобы сменить тему оформления в самой системе.
Работаешь и видишь - окошки серым подсвечены: значит рабочий профиль. светло зеленым - развлекательный профиль. и т.п.

**Comment by Allexin** [comment]
This idea is very hard in realization and can' t work properly on all platforms.
I found better way to show current profile - set background color of notification window. It's works more predictable.
