### ISSUE TITLE
Сборка в QT Creator

### ISSUE THREAD

**Issue by monoflash** [Allexin/TrackYourTime#46]
Вывод приложения:

Запускается /TrackYourTime/build-TrackYourTime-Desktop_Qt_5_5_1_clang_64bit-Release/TrackYourTime.app/Contents/MacOS/TrackYourTime...
dyld: Library not loaded: /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
  Referenced from: /TrackYourTime/build-TrackYourTime-Desktop_Qt_5_5_1_clang_64bit-Release/TrackYourTime.app/Contents/MacOS/TrackYourTime
  Reason: Incompatible library version: TrackYourTime requires version 64.0.0 or later, but ApplicationServices provides version 1.0.0

Что я делаю не так?
MacOs 10.11.4
Qt Creator: http://p.jiq.ru/18hol+

Приложение собирается, но при попытке запуска выдаёт сообщение и завершается.
Если приложение опенсорс, и QT Creator надо как-то специально "готовить", то хотелось бы инструкции для "готовки".

**Comment by Allexin** [comment]
Мне неведомы причины данных проблем.
У меня обычный QtCreator и обычная макось... собирается обычным способом. :(

**Comment by Allexin** [comment]
Fixed in 0.9.2 release
