### ISSUE TITLE
Win7 x64: Некорректная работа с русским языком

### ISSUE THREAD

**Issue by Lenchik** [Allexin/TrackYourTime#49]
Win7 x64 SP1. Некорректная работа с русским языком (и необычными значками) в именах файлов, заголовках окон браузера. Вопросики в ромбике.

На примере страницы https://github.com/Allexin/TrackYourTime/wiki/Руководство-пользователя
![tyt-russian](https://cloud.githubusercontent.com/assets/2931130/13212902/0706a914-d956-11e5-8380-8b3c30a0ec14.png)

С именами файлов отслеженных приложений - то же самое.

**Comment by Allexin** [comment]
Принято. Исправим в следующей версии.

**Comment by Allexin** [comment]
Исправлено в 0.9.2.1
