### ISSUE TITLE
Invisible tray icon in Windows

### ISSUE THREAD

**Issue by zedxxx** [Allexin/TrackYourTime#5]
App started and worked normal, but tray icon is invisible:
![image 1](https://cloud.githubusercontent.com/assets/6298130/12530848/d5b2f48c-c1fc-11e5-9ae4-1a4400e5c05a.png)
OS: Windows 8.1 x64

**Comment by Allexin** [comment]
Thanks. I'll check it.

**Comment by Allexin** [comment]
This bug fixed in source. Win32 version available for binary download
