### ISSUE TITLE
Отладка скрипта: нежелательный перехват фокуса окна

### ISSUE THREAD

**Issue by Lenchik** [Allexin/TrackYourTime#50]
Непонятно, как отлаживать скрипт, если окно "Настройки приложения"  TrackYourTime всё время перехватывает фокус на себя 

Предполагается, что пользователь не работает с максимизированными окнами?
![tyt-russian2](https://cloud.githubusercontent.com/assets/2931130/13213013/da3edcfc-d956-11e5-806f-fc0c6cbe3c6e.png)

**Comment by Allexin** [comment]
Предполагается такой сценарий работы с отладкой:
Запускаем режим отладки, открываем нужные приложения, помещаем их окна так, чтобы они не перекрывали отладочную информацию. Кликаем на приложения и смотрим как меняется отладочная информация.
Работа с максимизированными окнами не предполагается.
