### ISSUE TITLE
Статистика

### ISSUE THREAD

**Issue by Serg-Norseman** [Allexin/TrackYourTime#51]
Если возможно, и если у вас будет время, реализуйте пожалуйста в статистике такую фичу: опциональное включение отображения времени бездействия за выбранный интервал вывода статистики. А также, было бы неплохо сделать опцию отображения графика статистики в логарифмическом режиме - графики иногда становятся более наглядными, особенно если можно переключиться - такой режим позволяет приемлемо видеть самые маленькие сегменты данных. С удовольствием бы помог с проектом (программа очень понравилась), но с C++ не "на ты". Для отображения графика в логарифмическом режиме могу помочь с  готовым классом на C#. Из него можно будет просто извлечь весь подходящий код.

**Comment by Allexin** [comment]
Может быть сделаете отдельное приложение для более детальной работой со статистикой? А я внутри своего приложения сделаю экспорт данных и вызов вашего приложения?
Объясню почему не хочу усложнять статистику внутри самого трэкера:
очевидно, что практически у каждого пользователя свое видение "правильной" статистики. Сделать мощную универсальную статистику не получится - это отдельная огромная и сложная задача.
Но если пользователи будут расширять статистику посредством создания внешних приложений - с одной стороны это никак не скажется на сложности кода трэкера, а с другой даст выбор в приложениях для просмотра статистики.
Самый простой способ реализовать это:
сделаю в стастики список внешних просмоторщиков, которые может сам пользователь устанавливать и прописывать.
и кнопку "внешний просмотр диапазона".
При нажатии на кнопку выбранный диапазон не только отображается в стандартной статистике, но также экспортируется во временный CSV файл, и запускается выбранное внешнее приложение с передачей имени CSV файла в параметрах

**Comment by Serg-Norseman** [comment]
Идея хорошая и совершенно правильная. Можно сделать такую программу. Но, на текущий момент, получится так, что ввод такой статистики, с моими фишками, затянется надолго. При наличии вашей программы, кроссплатформенной (что очень здорово), делать дополнительный инструмент привязывающий пользователя к .NET или Java, которыми я владею - не очень хорошо. Пусть сейчас есть и Mono, и CoreCLR вроде как работает на ОС, отличных от Windows - всё равно... А реализовать адекватную сопутствующую программу на основе Qt, как у вас - быстро не смогу. Придется наконец-то всерьез заняться изучением C++ ))) Нужно подумать.

**Comment by Allexin** [comment]
Я вам совершенно не рекомендую заморачиваться с кроссплатформой. :)))
Банальная сборка релиза, с запусками виртуальных машин занимает у меня пол дня. То есть просто скомпилировать код под все платформы, проверить его поверхностно и собрать его в паки.
У меня нет выбора, т.к. есть платформозависимый код.
Но в случае приложения по работе со статистикой лучше делать приложение на том же .NET или Java, чтобы не пришлось собирать код под каждую платформу. А кроссплатформенным сделать лишь скрипт, который будет под каждой ОС правильно запускать приложение. Считаю что это позволит избежать гемороя с деплоем на каждую платформу, т.к. скрипт запуска будет достаточно один раз написать и не трогать его, а само приложение одинаково под все платформы.

**Comment by Serg-Norseman** [comment]
Занятное предложение. Попробую в ближайшее время набросать прототип программы. Посмотрю, что из этого выйдет :)

**Comment by tonal** [comment]
Полностью согласен с Allexin. Лучше сделать экспорт всей информации в несколько общеизвестных форматов:
JSON, XML. Возможно CSV, но тут, по ходу одним файлом не ограничиться...
А вот над ними можно делать статистику хоть в C#, хоть в R, хоть Python или вовсе Excel/Calc. :)
Хотя, если формат сохранения будет тоже общеизвестен - тот же SQL, например, то его можно и извне прочитать. :)
