### ISSUE TITLE
Постоянно появляются уведомления

### ISSUE THREAD

**Issue by divizdev** [Allexin/TrackYourTime#52]
Windows 10. Поставил обновление с 9.0 -> 9.2. Постоянно появляется уведомление "[название профиля]:Без категории". При этом в 9.0 в настройках я убирал "показывать уведомления". При этом если в трее для иконки не хватило место, она "спряталась", то убрать эти уведомления невозможно. Пришлось отключать уведомления настройками самой Windows

**Comment by Allexin** [comment]
Новая система уведомлений, соответственно настройки изменились.
В винде есть возможность показать все значки в трее. После показа всех значков вы сможете нормально получить доступ к настройкам приложения.
