### ISSUE TITLE
Win7 x64: Переход на 0.9.2.1 убил все категории

### ISSUE THREAD

**Issue by Lenchik** [Allexin/TrackYourTime#55]
Переход с 0.9.2 на 0.9.2.1 убил все категории. 
Просто заменил все файлы файлами из архива.

Аналогичный переход с 0.9.0 на 0.9.2 ничего не убивал

**Comment by Allexin** [comment]
Интересно.
1) Проверьте пожалуйста настройки, не слетел ли путь до БД.
2) Посмотрите пожалуйста список файлов в каталоге с БД и скажите их имена и размеры.

**Comment by Lenchik** [comment]
Визуально не слетел. Но программа сделала копию рядом с ним db.bin_
Этим файлом я заменил тот сброшенный новый db.bin.
В результате в настройках категорий всё ещё видны старые вопросики на месте неанглийских букв (#49), но зато на отладке скриптов русские буквы и значки разные нормально теперь отображаются.
Может быть, программа чистила базу на предмет архивных записей с русским и убила её так?

**Comment by Allexin** [comment]
Что произошло - понятно, но не понятно почему...
С русскими буквами это не связано.
При конвертации БД в новую версию приложение не смогло переписать старую версию. Не было доступа по каким-то причинам. Даже не знаю с чем это может быть связано... Ветку закрываю пока.

По поводу русских букв которые были сохранены ранее - они так и останутся кракозябрами. Они в таком виде уже сохранились и тут ничего сделать нельзя, потому что они в БД уже кракозябрами пришли. Фикс с юникодом касается только новых записей.
