### ISSUE TITLE
WinXP SP3: 0.9.2.1 не стала работать

### ISSUE THREAD

**Issue by Lenchik** [Allexin/TrackYourTime#56]
Предыдущие версии работали.
1. На программу заругался брандмауэр (огромная редкость на той машине, вообще считал, что он там отключен). Это, кстати, могло быть причиной блокирования доступа к базе, которую он тоже убил, как на Win7 было (судя по уменьшившемуся размеру файла).
2. Заругался на отсутствие msvc*120. Жаль что с каждым релизом они не идут. Взял из 0.9.0. На это ругаться перестал.
3. Потом вообще не запустился. Полноценного лога ошибки я не нашел. То, что винда предложила как файл сподробностями во временной папке - во вложении.
[66e4_appcompat.txt](https://github.com/Allexin/TrackYourTime/files/148269/66e4_appcompat.txt)

**Comment by Allexin** [comment]
1. Это понятно. ДОбавилась работа с сетью для получения информации об обновлении. 
   А как это могло повлиять на порчу БД? Она у вас на сетевом диске?
2. Не все либы в сборке - это косяк. Исправлю.
3. Для получения лога надо вот так запустить: TrackYourTime.exe > log.txt

**Comment by Lenchik** [comment]
1. Задержка при доступе к диску, к файлу. Вы же сказали в https://github.com/Allexin/TrackYourTime/issues/55#issuecomment-188949605

> При конвертации БД в новую версию приложение не смогло переписать старую версию. Не было доступа по каким-то причинам.

Задержка какая-нибудь. Как идея.
3. Как получу - пришлю

**Comment by Allexin** [comment]
1. Брэндмауэр не должен мешать.
2. Если есть сложности - не тратьте силы.
   Мне удалось воспроизвести баг с сломанной БД. В ближайшее время разберусь, пока не обновляется.
   Вопрос: 
   при переходе на новую версию БД приложение делает бэкап. Он выглядит вот так:
   db.bin.version.1 или db.bin.version.2
   Он у вас появился?

**Comment by Lenchik** [comment]
появился.
Программа вообще не хочет с XP работать. Даже с dll'ками. Я откатился на 0.9.2.

А по поводу убийства базы: Два разных компа, с разными операционками, с неограниченными в правах доступа пользователями, с базами в папках на несистемных дисках (в обоих случаях в папках с программой) - и база мрёт при обновлении...

**Comment by Allexin** [comment]
Спасибо. Благодаря вам нашел критичную ошибку в конвертации БД.
Старая БД не убилась при конвертации. Вы ее можете восставить. 
Бэкап находится либо в файле db.bin_ либо db.version.1 либо db.version.2
Собственно это файл БД до обновления версии. Только не подменяйте файлы с запущенным TrackYourTime. При закрытии или по таймеру опять вернет битую. Перед подменой надо закрыть приложение.
В ближайшие полчаса залью сборку с исправленным багом.

**Comment by Allexin** [comment]
Попробуйте эту сборку:
https://github.com/Allexin/TrackYourTime/releases/download/0.9.2.1/TrackYourTime_0_9_2_1_Win32.zip
Проверял на 32 битной XP - всё работало как надо.

**Comment by Lenchik** [comment]
Попробовал - работает
