### ISSUE TITLE
Расширение сбора статистики в Chrome: группировка по домену

### ISSUE THREAD

**Issue by vindi-r** [Allexin/TrackYourTime#62]
А как насчет сделать возможность группировать субдомены для отдельных доменов?
Объясню, почему возник вопрос. Для Вконтакте могут прислать ссылку vk.com/?some_request
или картинку pp.vk.me или картинку cs627928.vk.me/
Понятно, что все это относится к одному ресурсу.
Хотелось бы иметь возможность группировки таких сайтов под единый шаблон, отдаваемый в трекер.

**Comment by Allexin** [comment]
Хорошая мысль. Можно сделать regexp для активностей. Соответственно, все что попадает под regexp - добалвяется к нему, а не в отдельную активность. 
Сделаю.

**Comment by Allexin** [comment]
Теперь можно запускать кастомный скрипт как последний шаг в трэкинге. 
Кастомный скрипт теперь не отдельный режим.

Пример скрипта для объединения(подмены) доменов:
function parseData(appName, appTitle, trackingResult, currentOS){
  if (trackingResult.indexOf("pp.userapi.com")==0)
    return "vk.com";
  return trackingResult;
}

ПОка только в девелоп бранче
