### ISSUE TITLE
Альтернативный вариант Idler'a

### ISSUE THREAD

**Issue by alexrett** [Allexin/TrackYourTime#66]
Как вариант получать юзерскую активность можно еще вот таким способом:
getIdleTime() будет возвращать кол-во секунд НЕактивности. Таким образом можно сэкономить на треде с детекцией клавиатуры и не сравнивать позиции курсоров.

```
#ifdef Q_OS_WIN
#include <windows.h>

int getIdleTime()
{
    LASTINPUTINFO li;
    li.cbSize = sizeof(LASTINPUTINFO);
    GetLastInputInfo(&li);
    DWORD te = GetTickCount();
    int elapsed = (te - li.dwTime)/1000;
    return elapsed;
}

#endif


#ifdef Q_OS_LINUX
#include <time.h>
#include <stdio.h>
#include <unistd.h>
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/extensions/scrnsaver.h>

int getIdleTime() {
        time_t idle_time;
        static XScreenSaverInfo *mit_info;
        Display *display;
        int screen;
        mit_info = XScreenSaverAllocInfo();
        if((display=XOpenDisplay(NULL)) == NULL) { return(-1); }
        screen = DefaultScreen(display);
        XScreenSaverQueryInfo(display, RootWindow(display,screen), mit_info);
        idle_time = (mit_info->idle) / 1000;
        XFree(mit_info);
        XCloseDisplay(display);
        return idle_time;
}
#endif

#ifdef Q_OS_MAC
#include <ApplicationServices/ApplicationServices.h>

int getIdleTime() {
    CFTimeInterval timeSinceLastEvent = CGEventSourceSecondsSinceLastEventType(kCGEventSourceStateHIDSystemState, kCGAnyInputEventType);
    return timeSinceLastEvent;
}
#endif

}
```

**Comment by Allexin** [comment]
И под линуксом не будут нужны права на чтение из девайсов.
Спасибо за готовую реализацию. Имплементирую при первой возможности.

**Comment by f2404** [comment]
А вариант для линукса сработает без установленного `xscreensaver`?

**Comment by Allexin** [comment]
нет, не сработает.
но это расширение есть во всех репозиториях под распространенные дистрибутивы.
и в большинстве систем(во всех?) установлено по умолчанию. Полагаю придется постараться, чтобы найти систему без этого расширения.

**Comment by f2404** [comment]
В Arch Linux `xscreensaver` не устанавливается по умолчанию, и у меня он не установлен.
Правда, файл `/usr/include/X11/extensions/scrnsaver.h` в системе есть, он принадлежит пакету `libxss` (который тоже не обязательный).

**Comment by Allexin** [comment]
Ну тут вопрос, что меньшее из зол - давать приложениями под пользователем права на чтение устройств или установить один пакет из репозитория.
Я лично за второй вариант. Потому что под первый вариант может пролезть какой нибудь кейлогер...

**Comment by Allexin** [comment]
Переделал. Тестил пока только под линуксом. Под другие ОС даже собирать не пробовал.
Пока лежит в Develop бранче. Как потестирую сборку под всеми ОС - переедет в master.
Спасибо!
