### ISSUE TITLE
Автообновление окна Статистика

### ISSUE THREAD

**Issue by FrSaSA** [Allexin/TrackYourTime#68]
Если, возможно, было б очень удобно, если бы окно Статистика обновлялось автоматически. 
(обновлять в момент открытия окна, и через небольшой интервал)
Например: можно обновлять данные в окне Статистика раз в минуту или раз в 5 секунд...

А то постоянно нажимать кнопку "Обновить", очень изматывает.

**Comment by agarkoff** [comment]
Полезная функция была бы.

**Comment by Allexin** [comment]
Это уже было сделано и было убрано, т.к. засоряет интерфейс, но по факту функция не нужная.
Я подумаю над этим. Вероятнее всего автообновление вернется, но пока не могу точно сказать в каком виде.

**Comment by agarkoff** [comment]
Как автообновление может засорять интерфейс? Оно не требует никаких опций
для настройки.

21 июня 2016 г., 17:41 пользователь Allexin notifications@github.com
написал:

> Это уже было сделано и было убрано, т.к. засоряет интерфейс, но по факту
> функция не нужная.
> Я подумаю над этим. Вероятнее всего автообновление вернется, но пока не
> могу точно сказать в каком виде.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/Allexin/TrackYourTime/issues/68#issuecomment-227461344,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAoJpXQ4x4ybsRWivPg5jXnFWIvQzBsZks5qN_gVgaJpZM4Iemgn
> .

## 

Станислав Агарков

**Comment by Allexin** [comment]
Галка "Автообновление" и поле для указания периода.
Делать автообновление по умолчанию включенным без возможности выключить - это не вариант. Потому что нормальные юзкейсы вообще автообновление не предполагают - т.к. оно не нужно и является скорее баловством, чем необходимым инструментом.

**Comment by agarkoff** [comment]
Открываешь окно Статистика, а там старые данные и кнопка Обновить. И
непонятно то ли данные в окне свежие, то ли нет. На всякий случай всегда
приходится жать кнопку Обновить. Как минимум необходимо сделать
автообновление статистики при получении окном фокуса.

22 июня 2016 г., 8:27 пользователь Allexin notifications@github.com
написал:

> Галка "Автообновление" и поле для указания периода.
> Делать автообновление по умолчанию включенным без возможности выключить -
> это не вариант. Потому что нормальные юзкейсы вообще автообновление не
> предполагают - т.к. оно не нужно и является скорее баловством, чем
> необходимым инструментом.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/Allexin/TrackYourTime/issues/68#issuecomment-227647147,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAoJpckwp8eTXJEgFaaeApIgUvPEFFr7ks5qOMfKgaJpZM4Iemgn
> .

## 

Станислав Агарков

**Comment by FrSaSA** [comment]
Честно, не оч. понимаю, почему "Автообновления" является баловством..
вот, например, мой типичный case (и мне, почему то кажется, что так у многих пользователей происходит):
- два монитора на всех окна с работой, в дальнем углу окно стастистики из TrackYouTime
- сижу работаю и вдруг.... приуныл... (ну, бывает)
- сунулся в Youtube, на 5 минуточек, чтоб передохнуть, новсти, да то-сё..
- а окно статистики висит -> даавит! и одного взгляда в угол досточно, чтобы понять, что уже 40! минут в Youtube, что уже полоска отдыха, больше чем полоска работы, и она всё растёт, прям на глазах, давит, давит на совесть.. мол работай, работай - лентяй!
- закрываешь Youtube продолжаешь работать...
- Profit!
  ....

а если, как сейчас: 
сам открой, да сам обнови, ну так и зависаешь на Youtube, да на Habr-e, по 1.5 часа и более... ..ничего ведь не давит, всё хорошо, токо потом, как обновишь, ох! да как опомнишся, и до двух ночи работу наверстываешь... нехорошо так...

(понятно, что самодисциплина должна быть, и ответственность, и самоконтроль, 
но это ведь уже совсем другая история)

а по поводу засорения интерфейса, так в настройки её спрятать, 
каждый ведь сам для себя будет настраивать, один раз настроил и на всю жизнь.. больше её трогать и не надо...

**Comment by Allexin** [comment]
Сделал автоматическое обновление статистики при открытом окне, если установлена дата сегодняшнего дня.
Настройку делать не стал, вместо этого реализовал концепцию частичного обновления, что позволяет менять только часть данных, которые собственно и изменились, а не пересчитывать всё.
Ну и заодно немного поменял алогоритм подсчета статистики, что в общем случае на порядки увеличило скорость расчета полной статистики.

Пока только в девелоп бранче

**Comment by agarkoff** [comment]
Спасибо!
