### ISSUE TITLE
Add portable mode

### ISSUE THREAD

**Issue by Allexin** [Allexin/TrackYourTime#74]
Hello Alexander,

I came upon your program Track Your Time, tested version 0.9.2.1 on Windows 8 x64 and liked it- cross-platform, open-source and feature-rich. However I have a suggestion if you plan to continue the development of Track Your Time in the future- an option to use Track Your Time in portable mode. What I mean- now Track Your Time saves settings in Windows Registry:

HKEY_CURRENT_USER\Software\SRFGames\TrackYourTime

so I suggest a command-line parameter, for example:

TrackYourTime.exe -portable
TrackYourTime.exe --portable
TrackYourTime.exe /portable
TrackYourTime.exe /p

which forces Track Your Time to save settings not in Windows Registry but in program folder. Such an option to run Track Your Time in portable mode will increase the flexibility of the program- the user would be able to carry Track Your Time on external flash drive with all its data and settings and use it on other machines.

Best regards,

Asen

**Comment by Allexin** [comment]
I do not like idea with portable key.
Maybe check file existence?
E.g: file portable.ini exists(even empty) - write/read settings in taht file. if not exists - write/read to system specified configs.

**Comment by Allexin** [comment]
Hm...
Portable feature already done, i miss it.
How to use:
You can create OS specific config:
settings_<OSName>.conf
If OS specific config not exists, app use default config:
settings.conf
if default config not exists - app use system specific config(e.g. registry in windows)

OSName:
Windows
Linux
MacOSX
P.S.
Remember: Linux and MacOSX - case sensitivity OS

**Comment by smaragdus** [comment]
@Allexin 

Thank you very much for implementing portable mode! I have just tested it (on Windows 8 x64) and it works! I deleted the registry keys, created empty 'settings.conf' file in program folder and **Track Your Time** used it. Also it managed to open my old database created by version **0.9.2.1**.

However I noticed that now the tray icon looks a bit different:

**Track Your Time** version **0.9.2.1**:
![track your time 0 9 2 1 - tray - 2017-12-08 - 001](https://user-images.githubusercontent.com/9025757/33754178-b94e4a54-dbf3-11e7-9e44-b42f4ed45ddf.png)
**Track Your Time** version **0.9.2.5**:
![track your time 0 9 2 5 - tray - 2017-12-08 - 001](https://user-images.githubusercontent.com/9025757/33754206-d008ab9a-dbf3-11e7-8211-f6483490c966.png)
For me the old tray icon looks better.

I would like to ask- would it be possible to add an option to export 'Export categories to HTML' and 'Export applications to HTML'?

Regards

**Comment by Allexin** [comment]
> Also it managed to open my old database created by version 0.9.2.1.

Backward compatibility - important thing in this kind of app.

> For me the old tray icon looks better.

This is same icon, but in another resolution. Why your OS want this icon layer - i do not know. You can remove multiresolution icon: remove files data/icons/main.ico and data/icons/main_gray.ico
I have not plans to fix it because i have not clear understanding of tray icon behavior.

> I would like to ask- would it be possible to add an option to export 'Export categories to HTML' and 'Export applications to HTML'?

I have not any plans to improve TrackYourTime app. At this moment its good app and its fully operational. I have not any reasons to do it. I am understand - many users have requests for new features, but its impossible for me to waste more time on it. Sorry for that.
