### ISSUE TITLE
new feature: show how many time was spent in total

### ISSUE THREAD

**Issue by swedik** [Allexin/TrackYourTime#79]
For example, In statistics I choose Today and I want to see total sum of time spent on computer.

Thanks!

**Comment by Allexin** [comment]
Done. In Develop branch for now.

**Comment by swedik** [comment]
Thank you very much, but can you also advice howto compile your source code on linux from development branch? Before I just downloaded stable version and it worked. Thanks.

**Comment by Allexin** [comment]
I have a plan to release new version in 5 days.
Just wait release, there will be many improvements.

**Comment by swedik** [comment]
thanks Allexin!
