### ISSUE TITLE
Font scaling on MacBook Pro 15 Retina (A1398) with Windows 10 

### ISSUE THREAD

**Issue by andreichernov** [Allexin/TrackYourTime#8]
![-2016-01-23 20_14_59](https://cloud.githubusercontent.com/assets/1557729/12531549/a679afd2-c20e-11e5-9787-aabb3552a237.png)
Bad font scaling on MacBook Pro 15 Retina (A1398) with Windows 10

**Comment by Allexin** [comment]
Can you make screenshots for Applications and Statistics windows?

**Comment by andreichernov** [comment]
Yes:
![apps](https://cloud.githubusercontent.com/assets/1557729/12536502/71e94070-c2b8-11e5-8bdd-42bc3009d38d.png)
![stat](https://cloud.githubusercontent.com/assets/1557729/12536506/8fbef086-c2b8-11e5-8ac1-2ecca63a26ca.png)

**Comment by Allexin** [comment]
Thank you

**Comment by Allexin** [comment]
Fixed in 0.9.2 release
