### ISSUE TITLE
udev - FAILED

### ISSUE THREAD

**Issue by kuraleb** [Allexin/TrackYourTime#87]
Добрый день.

Получаю следующие ошибки

> $ ./checksystem
> X Window System - OK
> udev - FAILED
> /dev/input/by-id/*keyboard* not found
> keyboard not found
> How to fix: plug keyboard
> udev failure is non critical. Time tracker can work without fix this failure, but sleep mode will not work.

Как можно решить данную проблему? Спасибо.

**Comment by Allexin** [comment]
Это в последней версии? 
Если это последняя версия - просто проигнорируйте. Я вообще думал что убрал отткуда эту проверку, но мог и забыть.
Если предыдущая версия - то надо в udev прописывать приложению права на чтение клавиатуры. Как это делать - не подскажу. Информация из документации уже удалена. Используйте последнюю версию.

**Comment by kuraleb** [comment]
Нет, не последняя версия.
Последняя вовсе не захотела запускаться, в виду того, что у меня Debian Stretch и крайняя версия QT 5.7, а приложению требовала 5.8 и выше.

Пытался поставить пакеты с QT5.9 от тестовой версии, но она ломала все зависимости.

Сейчас запустил саму программу, вроде работает. 

Надеюсь проблем больше не будет.

Спасибо.

**Comment by Allexin** [comment]
Не будет работать сон. udev нужен чтобы понять, что клавиатуру давно не тыкали и надо перестать считать время. В остальном будет работать.
Новая версия берет инфу из скринсейвера и доступа к udev не требует. Она лучше. Она безопаснее. Это большой апдейт был и имеет смысл использовать его.
Вы можете собрать приложение самостоятельно из qt 5.7. 
Никаких зависимостей связанных с новой версией добавлено не было, так что должено собраться нормально. Если не соберется - я могу поправить, чтобы собиралось.

**Comment by kuraleb** [comment]
> $ make
> g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SCRIPT_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtScript -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o main.o main.cpp
> main.cpp: In function ‘int main(int, char**)’:
> main.cpp:96:16: error: ‘XScreenSaverInfo’ does not name a type
>          static XScreenSaverInfo *mit_info;
>                 ^~~~~~~~~~~~~~~~
> main.cpp:99:9: error: ‘mit_info’ was not declared in this scope
>          mit_info = XScreenSaverAllocInfo();
>          ^~~~~~~~
> main.cpp:99:42: error: ‘XScreenSaverAllocInfo’ was not declared in this scope
>          mit_info = XScreenSaverAllocInfo();
>                                           ^
> main.cpp:102:76: error: ‘XScreenSaverQueryInfo’ was not declared in this scope
>          XScreenSaverQueryInfo(display, RootWindow(display,screen), mit_info);
>                                                                             ^
> Makefile:336: ошибка выполнения рецепта для цели «main.o»
> make: *** [main.o] Ошибка 1
> 

у меня что-то вроде такого выходит
