### ISSUE TITLE
QT 5.8 for Debian

### ISSUE THREAD

**Issue by kuraleb** [Allexin/TrackYourTime#88]
Добрый день.

У меня Debian Stretch и крайняя версия QT 5.7, а приложение требует 5.8 и выше.

Пытался поставить пакеты с QT5.9 от тестовой версии, но она ломала все зависимости.

Возможно ли как то обойти проблему? Спасибо.

**Comment by Allexin** [comment]
Пересоберите приложение из исходников из qt 5.7
Должно быть достаточно простого запуска qmake в каталоге проекта

**Comment by kuraleb** [comment]
qmake требует параметр.
Какой следует ввести?

**Comment by Allexin** [comment]
qmake ./TrackYourTime.pro

Только перед этим заберите свежие исходники, там в файле проекта опечатка была. Или можете сами поправить 34 строку в файле TrackYourTIme.pro

Плюс если у вас по умолчанию установлен qmake от Qt4 - надо полный путь до пятого qmake указывать.

После того как qmake отработает запускаем 
make и получаем файл TrackYourTime. Его и используем.

**Comment by kuraleb** [comment]
Спасибо.
Собралось.
Заработало.

Пришлось правда еще либу libxss-dev доустанавливать.

И не подцепилась локализация, не отоброжается иконка в трее.

**Comment by Allexin** [comment]
Каталог data надо перенести в рабочку папку приложения

**Comment by kuraleb** [comment]
Перенес. И собрал заного.

Проблема с иконками и локализацией решилась, но вот обратил внимание, что режим "афк" не срабатывает. Счет статистики идёт и в моё отсутствие.

**Comment by kuraleb** [comment]
Перенес. Собрал. Заработало.
Спасибо.

**Comment by kuraleb** [comment]
Дело оказалось не в этом.
Если запускать исполняемый файл не из папки ситуация повторяется.
Дописал скрипт, который производит вход в директорию программы.

**Comment by Allexin** [comment]
Ну я не говорил "в папку с программой". Я говорил "в рабочую папку".
