### ISSUE TITLE
Как можно задонатить?

### ISSUE THREAD

**Issue by kuraleb** [Allexin/TrackYourTime#89]
Отличное приложение.

Как можно задонатить для выражения своей благодарности?)

**Comment by Allexin** [comment]
Рад что вам настолько пришлось по душе приложение. :)
Централизованного и удобного способа доната нет.
Если есть желание - можете перевести по реквизитам на счет в сбере(можно сделать через сбербанк онлайн, например):
Сбербанк России
БИК: 043601607
Счет карты: 40817810554403314519
Басов Александр Валерьевич

**Comment by kuraleb** [comment]
Ох и суровая у неё комиссия.
200% от отправленного

**Comment by Allexin** [comment]
Это у кого так?

**Comment by kuraleb** [comment]
с Qiwi

**Comment by Allexin** [comment]
Ну эти ребята славятся. Не думал что ими еще кто-то пользуется.

**Comment by kuraleb** [comment]
С такой крутой я только у Сбера сталкивался. У Альфа демократичней комиссия к примеру...
Использую, так как проще в использовании чем PayPal

**Comment by Allexin** [comment]
О. Есть счет в альфа банке. :)
ФИЛИАЛ «НИЖЕГОРОДСКИЙ» АО «АЛЬФА-БАНК»
БИК 042202824
40802 810 7 2939 0000986

**Comment by Allexin** [comment]
Спасибо!
